name: rhbrunetto
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_route: ^6.1.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  json_annotation: ^4.8.0

dev_dependencies:
  auto_route_generator: ^6.1.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/MavenPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/MavenPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MavenPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MavenPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MavenPro-Black.ttf
          weight: 900