name: Flutter Web
on:
  push:
    branches:
      - website
      
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      BASE_HREF: /rhbrunetto/
      TOKEN: ${{secrets.TOKEN}}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.TOKEN }}
          persist-credentials: false
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - run: flutter --version
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href=${{ env.BASE_HREF }}
      
      - run: |
          cd build/web
          git init
          git config --global user.email ricardo@rhbrunetto.com
          git config --global user.name rhbrunetto
          git status
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git remote add origin https://${{ env.TOKEN }}@github.com/rhbrunetto/rhbrunetto.git
          git push origin gh-pages -f
